// Code generated by ent, DO NOT EDIT.

package ent

import (
	"changeme/ent/image"
	"changeme/ent/note"
	"changeme/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescDeleted is the schema descriptor for deleted field.
	imageDescDeleted := imageFields[2].Descriptor()
	// image.DefaultDeleted holds the default value on creation for the deleted field.
	image.DefaultDeleted = imageDescDeleted.Default.(bool)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() uuid.UUID)
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescDeleted is the schema descriptor for deleted field.
	noteDescDeleted := noteFields[4].Descriptor()
	// note.DefaultDeleted holds the default value on creation for the deleted field.
	note.DefaultDeleted = noteDescDeleted.Default.(bool)
	// noteDescTitle is the schema descriptor for title field.
	noteDescTitle := noteFields[5].Descriptor()
	// note.DefaultTitle holds the default value on creation for the title field.
	note.DefaultTitle = noteDescTitle.Default.(string)
	// noteDescID is the schema descriptor for id field.
	noteDescID := noteFields[0].Descriptor()
	// note.DefaultID holds the default value on creation for the id field.
	note.DefaultID = noteDescID.Default.(func() uuid.UUID)
}
