// Code generated by ent, DO NOT EDIT.

package ent

import (
	"changeme/ent/note"
	"changeme/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescDeleted is the schema descriptor for deleted field.
	noteDescDeleted := noteFields[4].Descriptor()
	// note.DefaultDeleted holds the default value on creation for the deleted field.
	note.DefaultDeleted = noteDescDeleted.Default.(bool)
	// noteDescID is the schema descriptor for id field.
	noteDescID := noteFields[0].Descriptor()
	// note.DefaultID holds the default value on creation for the id field.
	note.DefaultID = noteDescID.Default.(func() uuid.UUID)
}
