// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}
