// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
