// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';

export function CreateProject(arg1:string):Promise<string>;

export function GetDB():Promise<ent.Client>;

export function GetProjects():Promise<Array<string>>;
