// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ent} from '../models';

export function CreateNote(arg1:string):Promise<main.Note>;

export function CreateProject(arg1:string):Promise<string>;

export function GetDB():Promise<ent.Client>;

export function GetNote(arg1:number):Promise<main.Note>;

export function GetProjects():Promise<Array<string>>;

export function ListNotes():Promise<Array<main.Note>>;

export function UpdateNote(arg1:number,arg2:string):Promise<main.Note>;
