// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateImageFromLocal(arg1, arg2) {
  return window['go']['main']['App']['CreateImageFromLocal'](arg1, arg2);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetImageList() {
  return window['go']['main']['App']['GetImageList']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function SearchByTitle(arg1) {
  return window['go']['main']['App']['SearchByTitle'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
