name: Wails build

on:
  repository_dispatch:
    types: [build-app]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'njournal'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'njournal'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'njournal'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22'