name: Wails build

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - platform:  'windows/amd64'
            os: 'windows-latest'
          - platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: 'njournal'
          build-platform: ${{ matrix.build.platform }}
          nsis: true
          package: true
          go-version: '1.24.1'
          node-version: '22.14.0'