name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract version from JSON
      id: get_version
      run: echo "::set-output name=VERSION::$(jq -r '.info.productVersion' wails.json)"
      
    - name: Set up Git config
      run: |
        git config --global user.email "tomato.wonder.life@gmail.com"
        git config --global user.name "nasum"
        
    - name: Check if tag already exists
      id: check_tag
      run: |
        if git rev-parse ${{ steps.get_version.outputs.VERSION }} >/dev/null 2>&1; then
          echo "::set-output name=EXISTS::yes"
        else
          echo "::set-output name=EXISTS::no"
        fi

    - name: Create and push tag if not exists
      if: steps.check_tag.outputs.EXISTS == 'no'
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        git tag $VERSION
        git push origin $VERSION
